docker + podman utils commands

diff --git a/bins/choose-container b/bins/choose-container
--- a/bins/choose-container
+++ b/bins/choose-container
@@ -24,7 +24,18 @@ done
 
 shift $((OPTIND-1))
 
-output=$(docker ps $docker_ps_args --format "{{.ID}}|{{.Names}}|{{.Image}}|{{.Ports}}")
+
+if [ $# -lt 1 ] ; then
+    >&2 echo "Missing containers command argument"
+    exit 1
+fi
+
+containers_cmd="$1"
+
+shift 1
+
+
+output=$("$containers_cmd" ps $docker_ps_args --format "{{.ID}}|{{.Names}}|{{.Image}}|{{.Ports}}")
 
 # create a printf format string, based on the max length of each field
 format_string=$(<<< $output awk -F"|" '
diff --git a/bins/container-exec b/bins/container-exec
--- a/bins/container-exec
+++ b/bins/container-exec
@@ -20,15 +20,26 @@ done
 
 shift $((OPTIND-1))
 
-container_id=$(choose-container $options "$*")
+
+if [ $# -lt 1 ] ; then
+    >&2 echo "Missing containers command argument"
+    exit 1
+fi
+
+containers_cmd="$1"
+
+shift 1
+
+
+container_id=$(choose-container $options "$containers_cmd" "$*")
 if [ $? -ne 0 ] ; then
     echo $container_id
     exit 1
 fi
 
-docker exec $container_id bash -c "echo 1" 2>&1 >/dev/null
+"$containers_cmd" exec $container_id bash -c "echo 1" 2>&1 >/dev/null
 if [ $? -eq 0 ] ; then
-    docker exec -it $container_id bash
+    "$containers_cmd" exec -it $container_id bash
 else
-    docker exec -it $container_id sh
+    "$containers_cmd" exec -it $container_id sh
 fi
diff --git a/bins/container-rm b/bins/container-rm
--- a/bins/container-rm
+++ b/bins/container-rm
@@ -20,10 +20,21 @@ done
 
 shift $((OPTIND-1))
 
-container_id=$(choose-container -a -m $options "$*")
-if [ $? -ne 0 ] ; then
-    echo $container_id
-    return
+
+if [ $# -lt 1 ] ; then
+    >&2 echo "Missing containers command argument"
+    exit 1
 fi
 
-docker rm -f $container_id
+containers_cmd="$1"
+
+shift 1
+
+
+container_id=$(choose-container -a -m $options "$containers_cmd" "$*")
+if [ $? -ne 0 ] ; then
+    echo $container_id
+    exit 0
+fi
+
+"$containers_cmd" rm -f $container_id
diff --git a/bins/container-rmi b/bins/container-rmi
--- a/bins/container-rmi
+++ b/bins/container-rmi
@@ -26,7 +26,18 @@ done
 
 shift $((OPTIND-1))
 
-choices=$(docker image ls | sed 1d)
+
+if [ $# -lt 1 ] ; then
+    >&2 echo "Missing containers command argument"
+    exit 1
+fi
+
+containers_cmd="$1"
+
+shift 1
+
+
+choices=$("$containers_cmd" image ls | sed 1d)
 
 if [ -z "$choices" ] ; then
     echo "No images found"
@@ -42,4 +53,4 @@ if [ -z "$choices" ] ; then
     exit 1
 fi
 
-echo "$choices" | awk '{print $3}' | xargs -r docker rmi
+echo "$choices" | awk '{print $3}' | xargs -r "$containers_cmd" rmi
diff --git a/bins/container-stoprm b/bins/container-stoprm
--- a/bins/container-stoprm
+++ b/bins/container-stoprm
@@ -20,11 +20,22 @@ done
 
 shift $((OPTIND-1))
 
-container_id=$(choose-container -m $options "$*")
+
+if [ $# -lt 1 ] ; then
+    >&2 echo "Missing containers command argument"
+    exit 1
+fi
+
+containers_cmd="$1"
+
+shift 1
+
+
+container_id=$(choose-container -m $options "$containers_cmd" "$*")
 if [ $? -ne 0 ] ; then
     echo $container_id
     exit 1
 fi
 
-docker stop $container_id
-docker rm $container_id
+"$containers_cmd" stop $container_id
+"$containers_cmd" rm $container_id
